### ISSUE TITLE
Create "Channels" adjustment

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#10]
Create an adjustment that goes one by one through the 5 Channel options

1. All
2. Alpha
3. R
4. G
5. B
<img width="393" alt="Screenshot 2022-05-19 at 15 45 53" src="https://user-images.githubusercontent.com/104977914/169297364-a584b9be-ee05-4a3e-88ce-ac3c33139f38.png">

**Comment by latenitefilms** [comment]
This is already available via the menubar actions.

**Comment by JennyMeissner** [comment]
Can you remind me where to find Menubar actions? I guess I haven't tested them at all yet.

**Comment by latenitefilms** [comment]
They're just under "FCP: Menu - File", etc.

**Comment by JennyMeissner** [comment]
I cannot find an adjustment for it, only the press actions.
Idea was to put everything under one dial to save space on touchscreen. :-)

**Comment by latenitefilms** [comment]
This should be possible, will have a play on Monday.

**Comment by latenitefilms** [comment]
This will be included in the next beta.
