### ISSUE TITLE
Create Distort adjustments

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#12]
Create Distort adjustments to distort 

1. Bottom Left X
2. Bottom Right X
3. Top Right X
4. Top Left X
5. Bottom Left Y
2. Bottom Right Y
3. Top Right Y
4. Top Left Y
One tick changes the value by 1,0 px

Pressing the dial should reset to zero px

**Question:** Any idea how to make use of Distort with a wheel widget? Could we separate the wheel into 4 sections -> if user's swipe starts from the bottom left on the wheel, he adjusts X&Y of the "Bottom Left" values simultaneoasly?

**Comment by latenitefilms** [comment]
Will tackle this next week.

**Comment by latenitefilms** [comment]
Distort adjustments will be included in the next beta.
