### ISSUE TITLE
Make Undo work when German keyboard layout is selected

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#14]
As a user who has German keyboard layout selected, I want that "Undo" press action from Menu - Edit group executes: Undo.

Strangely enough, for example "Select All" with French kb layout works just fine even though key:A is not in same position on keyboard.

**Comment by JennyMeissner** [comment]
actually, I noticed that I have Loupedeck commandset 4.0 selected. What role does the commandset play in CP app?

**Comment by latenitefilms** [comment]
> actually, I noticed that I have Loupedeck commandset 4.0 selected. What role does the commandset play in CP app?

CommandPost allows you to use any command set - unlike the current FCPX Loupedeck Plugin, it definitely doesn't "force" a user to use a specific command set. If you try to trigger an action that doesn't have a shortcut key assigned to it within the Command Editor, you'll get a macOS notification telling you, and if you click it it'll take you to the Command Editor allowing you to assign whatever you want to it.

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
