### ISSUE TITLE
Optional: Create your own profile for Loupedeck Marketplace

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#19]
It would be supercool if you can make your own profile version that contains either all the stuff you want to promote, or shows how you work in FCP. People are super eager to get profile options, from simple to overkill and I know they would love to see a profile by the Chris Hocking himself :-)

**Comment by latenitefilms** [comment]
I'm going to close this for now, and we can re-look at it once the CommandPost Loupedeck Plugin is wrapped up.
