### ISSUE TITLE
Saturation & Brighness adjustments are mixed up

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#21]
Note: this bug happened only on first dial rotation. Could not reproduce later anymore.

Bug in **color wheels adjustments**:

1. "Master Saturation" adjust Shadows Sat. 
2. "Shadows Sat" adjusts Highlights Sat.
3. "Highlights Sat" adjusts Shadows Sat

5. "Master Brightess" adjust Shadows Brightess.
6. "Shadows Brightess" adjusts Highlights Brightess
7. "Highlights Brightess" adjusts Shadows Brightess

Midtones works correctly.

**Comment by JennyMeissner** [comment]
while you're at it, rename Master -> Global?

**Comment by latenitefilms** [comment]
> Note: this bug happened only on first dial rotation. Could not reproduce later anymore.

I can't reproduce this, nor can I see any obvious way this could happen on the CommandPost side. My only GUESS it that for whatever reason Loupedeck was sending the wrong actions?

> while you're at it, rename Master -> Global?

Good spotting! Apple renamed it from Master to Global at some stage, and our internal functions are still called "Master" so I keep forgetting to use "Global" instead. Updated!
