### ISSUE TITLE
Create R G B adjustments for LD Live users

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#23]
Create adjustments to move the indicator on color wheels for R, G & B so that Loupedeck Live users can adjust the RGB values on color wheels **with dials**.

Create

1. Master Color Wheel R -> Display name: Global Red
2. Master Color Wheel G -> Display name: Global Green
3. Master Color Wheel B-> Display name: Global Blue
4. Shadows Color Wheel R -> Display name: Shadows Red
5. Shadows Color Wheel G -> Display name: Shadows Green
6. Shadows Color Wheel B-> Display name: Shadowsl Blue
7. Midtones Color Wheel R -> Display name: Midtones Red
8. Midtones Color Wheel G -> Display name: Midtones Green
9. Midtones Color Wheel B-> Display name: Midtones Blue
10. highlights Color Wheel R -> Display name: highlights Red
11. highlights Color Wheel G -> Display name: highlightss Green
12. highlights Color Wheel B-> Display name: highlights Blue

**Comment by latenitefilms** [comment]
This will be added in the next beta.
