### ISSUE TITLE
unresponsive actions in beta 6

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#24]
List of actions that seem to do nothing with beta 6:

1. Add Color Wheels Effect
2. Add Color Board Effect
3. Add Color Curves Effect
4. Add Hue Sat Effect
5. Toggle Color Corr Effects on/off
6. Toggle Fullscreen
7. Disable
8. tbc

**Comment by latenitefilms** [comment]
These are Keyboard Shortcut actiosn. Do you actually have something assigned to "Add Color Wheels Effect" in the Final Cut Pro Command Editor? If not, you should have seen a macOS notification like this:

![image](https://user-images.githubusercontent.com/22286696/169804852-8147478e-b557-4e3e-95bc-c1d7a898d411.png)

I'm going to close this issue for now, as I'm ASSUMING that you are just using a Command Set that doesn't have shortcuts assigned to these actions?
