### ISSUE TITLE
CommandPost not available in Workflow Extensions in beta7

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#27]
With beta 7, the Playhead adjustments don't work anymore, so maybe the workflow extension did not get added with installer.

**Comment by latenitefilms** [comment]
It's working fine here?

Do you still see CommandPost listed in the Workflow Extensions toolbar/menubar?

<img width="281" alt="image" src="https://user-images.githubusercontent.com/22286696/169907434-7d2e58d6-cf68-4d9a-9627-ebbfd654be24.png">

We added some code to make CommandPost forcefully make the CommandPost Workflow Extension as small as possible, so it's less obvious now when it's open.

I'm going to close this issue for now, but re-open it if you're still having issues.

**Comment by JennyMeissner** [comment]
Same with beta 8. 
A fresh installation of CP plugin does not install CP in Extensions.

Only this line in Terminal brings it back: 
pluginkit -a /Applications/CommandPost.app/Contents/PlugIns/CommandPost.appex

**Comment by latenitefilms** [comment]
We should be triggering this exact command when CommandPost launches for the first time for each version - so it should have the same effect. Do you have FCPX running when you install the new version of CommandPost?

**Comment by JennyMeissner** [comment]
Right, most likely FCP was running during installation. 🙄
Now the Extension appeared immediately after fresh install
