### ISSUE TITLE
Make own version of Jog wheel template

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#28]
The current "Jog" wheel page contains 

1. Move Playhead 1 farme
2. Move Playhead 10 farmes
3. Select Edit Point
depending on wheel rotation speed.

Replace the actions with CP plugin actions and just make a better version of it. Print CP logo to wheel template (I can send .psd file).

If there is a way to speed up the playhead exponentially to the wheel rotation speed, so that 
- slow rotation moves 1 frame, 
- faster rotation moves double speed, 
- faster rotation moves triple speed etc, 

then we can leave out "Select Edit" alltogether.

![FCPwheel_shuttle](https://user-images.githubusercontent.com/104977914/169897236-17aefbfc-beaa-4350-a6ff-bbaac00cd6ed.png)

**Comment by latenitefilms** [comment]
This will be included in the next beta.
