### ISSUE TITLE
Plugin Description text for Marketplace

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#29]
I'm happy if you can help to describe the CP plugin to give users an understanding what they get from installing it for Loupedeck.

We need

1. short description of 1 or 2 sentences for the card
2. long description with all info that user needs that shows when user clicks on the card
![cp_MP](https://user-images.githubusercontent.com/104977914/170012102-dce54d48-a871-495a-8d7e-e0c6be9608b5.jpg)

Note: Markdown option will be available shortly, so the text does not look like just one block anymore, as in current MP version.

**Comment by JennyMeissner** [comment]
Pictures unfortunately are not supported

**Comment by latenitefilms** [comment]
**Short Description:**
CommandPost is a free and open source macOS application that bridges between control surfaces and software that doesn’t support them natively. This plugin allows you to trigger CommandPost actions directly from Loupedeck devices, allowing you superior control of applications like Final Cut Pro.

**Long Description:**
CommandPost is a free and open source macOS application that bridges between control surfaces and software that doesn’t support them natively, such as Apple’s Final Cut Pro and Adobe’s After Effects.

It’s used by filmmakers, developers, scientists and macOS power users all over the world to seriously speed up mundane tasks through powerful and customisable automation tools.

For example, you can apply individual effects within Final Cut Pro or After Effects with the single tap of a button.

Powered by Lua (the same scripting language used by Blackmagic Fusion, Adobe Lightroom and even parts of Apple iOS), it’s insanely customisable and powerful.

It runs natively on Apple Silicon and is fully compatible with Hammerspoon.

For Loupedeck Users, CommandPost allows you complete control of Apple's Final Cut Pro. You can trigger individual effects, transitions, titles and generators. You have fine control over the Final Cut Pro playhead. You can access every Command Editor shortcut and menubar item. You can use knobs to change Blend Modes. It's insanely powerful.
