### ISSUE TITLE
Toggle Fullscreen unresponsive

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#31]
"Toggle Fullscreen" macro action is unresponsive in beta 8.
(In beta 7 it was working but jumped to timeline start and always showed the first frame of timeline)

**Comment by latenitefilms** [comment]
Toggle Fullscreen requires the Workflow Extension - is it running?

**Comment by JennyMeissner** [comment]
It is running after I entered the line in Terminal but no command arrives in Extension window fro pressing "Toggle Fullscreen". "Playhead" action work though.

**Comment by latenitefilms** [comment]
In this case we're not sending a command to the Workflow Extension, the Workflow Extension is basically just telling us what frame we're currently on. It's working fine here? I'm just using a single red frame for testing purposes:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/22286696/170145930-5c3c4e87-0852-472f-a7ca-ac0d25b2f184.png">

**Comment by latenitefilms** [comment]
I've made some improvements to the Workflow Extension which will hopefully solve these issues.

I'll close this issue for now and you can always re-open if you're still having problems with the next beta build.
