### ISSUE TITLE
Create a Fullscreen toggle action

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#4]
Create a fullscreen toggle action so that 

- pressing the button enlarges the **video panel** to fullscreen without playing the clip (stay on same frame in timeline)
- pressing the button again brings the video back to normal  (= Esc)

The goal is that user can do color grading on a fullscreen frame. By rotating the playhead dial, user can go to next frame(s).

**Comment by latenitefilms** [comment]
I'll add this tomorrow.

**Comment by latenitefilms** [comment]
"Toggle Fullscreen" will be included in the next beta.

**Comment by JennyMeissner** [comment]
Going Fullscreen moves 2 frames in timeline before showing the image -> What I see in Fullscreen is not what I had in viewer. 
We had same problem with Loupedeck. 
Any way to show the exact same image in Fullscreen as in Viewer window? Does the action still work as a toggle then?

**Comment by latenitefilms** [comment]
It was working fine on my Mac, but it could be performance related - what kind of Mac do you have?

Basically the way it currently works is we trigger the full screen menubar item, and as soon as the full screen mode is visible, we trigger spacebar to stop playback. If you have a slower machine, there could be a delay in detecting the window, and thus a delay in pressing spacebar.

I'm not sure there's any other workaround to prevent this - but I'll have a think and a look.

**Comment by latenitefilms** [comment]
Thinking about it... we MIGHT be able to use our fancy new Workflow Extension to work around this. Will test it out.

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
