### ISSUE TITLE
Create Trim adjustment

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#5]
Create Trim adjustment so that

- pressing a dial selects nearest edge of clip
- rotating the dial, trims the clip

If not possible, create Trim Left & Trim Right adjustments. 
1) selects left edge & trims
2)  selects right edge & trims

**Comment by latenitefilms** [comment]
This should already be possible by assigning "shortcuts" to the knob, but we can definitely make some specific actions for this to make setup easier.

**Comment by latenitefilms** [comment]
This will be included in the next beta.

**Comment by JennyMeissner** [comment]
At the moment, both Trim adjustments do the same: nudge the clip (move the whole clip l&r)

My idea was that first the left or right edge of a clip is selected, as in the shortcuts from screenshot (however, those shortcuts don't work for me, do they work for you?). Rotating the dial moves the edge of the clip left & right.

**Comment by latenitefilms** [comment]
The press actions select the left or right edge, then you can turn the knob to adjust.

There's no built-in FCPX method for selecting the nearest edge. We could potentially build this - but it's complicated. What if there's multiple clips above the primary storyline? How do we know which clip edge to select?

**Comment by latenitefilms** [comment]
I'm going to close this for now, as "selecting the nearest edge" is pretty complicated, once you have multiple clips on different storylines.
