### ISSUE TITLE
Remove questionmarks from adjustments (on dial strip)

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#6]
Some adjustments currently show questionmarks. If the questionamrks don't have a purpose to show frames or values, remove them, so that no questionmarks appear on dial strip of LD device.

Atm, e.g. Playhead and Favorite adjustments show questionmarks.
![279713042_520049763153971_1056484611834180958_n](https://user-images.githubusercontent.com/104977914/169045018-45ca6777-55ef-4c08-95cc-5220d6819e11.jpg)

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
