### ISSUE TITLE
Give descriptive names to "Favorite" adjustments

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#7]
Give descriptive names to "Favorite" adjustments so that I know what they are supposed to do.
Atm, they don't seem to work because it is unclear where to use them.
![279713042_520049763153971_1056484611834180958_n](https://user-images.githubusercontent.com/104977914/169045476-ca1c10d7-f008-40dc-be04-3efbe35418de.jpg)

**Comment by latenitefilms** [comment]
I've updated the repository's [README](https://github.com/CommandPost/LoupedeckPlugin), so that it's more clear what favourites do and how they work. Because they can be ANYTHING the only real solution is to leave it up to the user to assign an appropriate icon to the favourite.
