### ISSUE TITLE
Hide Extension status window 

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#8]
Try to hide Extension status window in the background so that it doesn't block valuable screen space on top of running FCP app. 
Even downsized, it is on the way.
<img width="950" alt="Screenshot 2022-05-19 at 15 17 06" src="https://user-images.githubusercontent.com/104977914/169291891-53b5d1a5-6d09-4e02-aab2-9d2e8b4d5d62.png">
.

**Comment by latenitefilms** [comment]
Unfortunately this is a limitation of Final Cut Pro Workflow Extensions.

As explained [here](https://help.commandpost.io/workflow-extension/workflowextension), I would just make it as small as possible, and drag to the edge of your screen so that it's out of the way.
