### ISSUE TITLE
Create "Blend Modes" adjustment

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#9]
Create an adjustment that goes one by one through the Blend Modes, following the order in FCP (starting with "Substract")
Pressing the dial resets Blend Mode to "Normal"

<img width="445" alt="Screenshot 2022-05-19 at 15 42 02" src="https://user-images.githubusercontent.com/104977914/169296354-a97cbef7-3f5b-440c-a445-3e62d822cc01.png">

**Comment by latenitefilms** [comment]
This will be added in the next beta.

**Comment by JennyMeissner** [comment]
Is there a way to make it work so that the dropdown in FCP doesn't open on every dial rotation?

**Comment by latenitefilms** [comment]
No, you need to open the popup to select the item - however, if you turn the wheel quickly, it won't pop up straight away.
